version: "2"

services:

  ghost:
    image: ghost
    volumes:
      - ghostdata:/var/lib/ghost/content
    environment:
      - url=${URL}
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghostdb
      - database__connection__password=${MYSQL_PASSWORD}
      - database__connection__database=ghostdb
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - DEFAULT_HOST=${DEFAULT_HOST}
      - VIRTUAL_PORT=2368
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - proxy
      - ghost
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb
    volumes:
      - ghostdb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ghostdb
      - MYSQL_USER=ghostdb
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - ghost
    restart: unless-stopped

volumes:
  ghostdb:
  ghostdata:

networks:
  proxy:
    external:
      name: nginx-proxy
  ghost:
